Repair /*With cascade="all"*/ ERROR E1Hibernate:38 - getE1ByID Error= org.hibernate.TypeMismatchException: Provided id of the wrong type for class gr.manousos.model.E1. Expected: class gr.manousos.model.E1Id, got class gr.manousos.model.E1expensesRemovedFromTotalIncomeId
/*With  property-ref="id" cascade="save-update"*/
[#|2013-06-06T21:45:39.358+0300|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=25;_ThreadName=Thread-2;|21:45:39,357
ERROR E1Hibernate:38 - getE1ByID Error=
org.hibernate.HibernateException: Unable to resolve property: id


Caused by: org.hibernate.PropertyNotFoundException: Could not find a
getter for tid in class gr.manousos.model.E1Id